[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
    "pybind11>=2.8.0",
]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
write_to = "src/psfmodels/_version.py"
